data_dir: gs://my-imagenet
dataset: tfds/imagenet2012:5.0.0
train_split: train
val_split: validation
model: gmixer_24_224
pretrained: false
initial_checkpoint: ''
resume: ''
no_resume_opt: false
num_classes: 1000
gp: null
img_size: 224
input_size: null
crop_pct: 0.9
mean: null
std: null
interpolation: ''
batch_size: 224
validation_batch_size_multiplier: 1

opt: adamw
opt_eps: 1.0e-06
opt_betas: null
momentum: 0.9
weight_decay: 0.067
clip_grad: 1.0
clip_mode: norm

sched: cosine
lr: 0.0008
lr_noise: null
lr_noise_pct: 0.67
lr_noise_std: 1.0
lr_cycle_mul: 1.0
lr_cycle_limit: 1
warmup_lr: 1.0e-06
min_lr: 1.0e-05
epochs: 600
epoch_repeats: 0.0
start_epoch: null
decay_epochs: 1.0
warmup_epochs: 20
cooldown_epochs: 10
patience_epochs: 10
decay_rate: 0.988

no_aug: false
scale:
- 0.08
- 1.0
ratio:
- 0.67
- 1.5
hflip: 0.5
vflip: 0.0
color_jitter: 0.4
aa: rand-m6-n4-mstd1.0-inc1
aug_splits: 0
jsd: false
reprob: 0.0
remode: pixel
recount: 3
resplit: false
mixup: 0.5
cutmix: 1.0
cutmix_minmax: null
mixup_prob: 1.0
mixup_switch_prob: 0.5
mixup_mode: batch
mixup_off_epoch: 0
smoothing: 0.1
train_interpolation: random
drop: 0.01
drop_connect: null
drop_path: 0.1
drop_block: null

bn_tf: false
bn_momentum: null
bn_eps: null
sync_bn: false
dist_bn: reduce
split_bn: false

model_ema: true
model_ema_force_cpu: false
model_ema_decay: 0.99992

seed: 42
log_interval: 50
recovery_interval: 0
checkpoint_hist: 10
workers: 4
save_images: false
amp: false
apex_amp: false
native_amp: false
channels_last: false
pin_mem: false
no_prefetcher: false
output: ''
experiment: ''
eval_metric: top1
tta: 0
local_rank: 0
use_multi_epochs_loader: false
torchscript: false
log_wandb: false
